"""add checks table

Revision ID: 7a86442e200c
Revises: bd3df236e470
Create Date: 2026-08-17 18:57:55.861579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a86442e200c'
down_revision: Union[str, Sequence[str], None] = 'bd3df236e470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expected_value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_id'), 'checks', ['id'], unique=False)
    op.create_index(op.f('ix_checks_name'), 'checks', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checks_name'), table_name='checks')
    op.drop_index(op.f('ix_checks_id'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
