"""add submitted_by to validation_runs

Revision ID: d58f8fe3f463
Revises: 309ff774524f
Create Date: 2026-08-20 08:10:23.833329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58f8fe3f463'
down_revision: Union[str, Sequence[str], None] = '309ff774524f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_runs', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'validation_runs', 'users', ['submitted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_column('validation_runs', 'submitted_by')
    # ### end Alembic commands ###
